#include <Crisp/Vulkan/Rhi/VulkanChecks.hpp>

#define STRINGIFY_CASE_RETURN(x)                                                                                       \
    case (x):                                                                                                          \
        return #x

namespace crisp::detail {
const char* toString(const VkResult result) noexcept {
    switch (result) {
        STRINGIFY_CASE_RETURN(VK_NOT_READY);
        STRINGIFY_CASE_RETURN(VK_TIMEOUT);
        STRINGIFY_CASE_RETURN(VK_EVENT_SET);
        STRINGIFY_CASE_RETURN(VK_EVENT_RESET);
        STRINGIFY_CASE_RETURN(VK_INCOMPLETE);
        STRINGIFY_CASE_RETURN(VK_ERROR_OUT_OF_HOST_MEMORY);
        STRINGIFY_CASE_RETURN(VK_ERROR_OUT_OF_DEVICE_MEMORY);
        STRINGIFY_CASE_RETURN(VK_ERROR_INITIALIZATION_FAILED);
        STRINGIFY_CASE_RETURN(VK_ERROR_DEVICE_LOST);
        STRINGIFY_CASE_RETURN(VK_ERROR_MEMORY_MAP_FAILED);
        STRINGIFY_CASE_RETURN(VK_ERROR_LAYER_NOT_PRESENT);
        STRINGIFY_CASE_RETURN(VK_ERROR_EXTENSION_NOT_PRESENT);
        STRINGIFY_CASE_RETURN(VK_ERROR_FEATURE_NOT_PRESENT);
        STRINGIFY_CASE_RETURN(VK_ERROR_INCOMPATIBLE_DRIVER);
        STRINGIFY_CASE_RETURN(VK_ERROR_TOO_MANY_OBJECTS);
        STRINGIFY_CASE_RETURN(VK_ERROR_FORMAT_NOT_SUPPORTED);
        STRINGIFY_CASE_RETURN(VK_ERROR_FRAGMENTED_POOL);
        STRINGIFY_CASE_RETURN(VK_ERROR_UNKNOWN);
        STRINGIFY_CASE_RETURN(VK_ERROR_OUT_OF_POOL_MEMORY);
        STRINGIFY_CASE_RETURN(VK_ERROR_INVALID_EXTERNAL_HANDLE);
        STRINGIFY_CASE_RETURN(VK_ERROR_FRAGMENTATION);
        STRINGIFY_CASE_RETURN(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
        STRINGIFY_CASE_RETURN(VK_PIPELINE_COMPILE_REQUIRED);
        STRINGIFY_CASE_RETURN(VK_ERROR_SURFACE_LOST_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR);
        STRINGIFY_CASE_RETURN(VK_SUBOPTIMAL_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_OUT_OF_DATE_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_VALIDATION_FAILED_EXT);
        STRINGIFY_CASE_RETURN(VK_SUCCESS);
        STRINGIFY_CASE_RETURN(VK_ERROR_INVALID_SHADER_NV);
        STRINGIFY_CASE_RETURN(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT);
        STRINGIFY_CASE_RETURN(VK_ERROR_NOT_PERMITTED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT);
        STRINGIFY_CASE_RETURN(VK_THREAD_IDLE_KHR);
        STRINGIFY_CASE_RETURN(VK_THREAD_DONE_KHR);
        STRINGIFY_CASE_RETURN(VK_OPERATION_DEFERRED_KHR);
        STRINGIFY_CASE_RETURN(VK_OPERATION_NOT_DEFERRED_KHR);
        STRINGIFY_CASE_RETURN(VK_ERROR_COMPRESSION_EXHAUSTED_EXT);
        STRINGIFY_CASE_RETURN(VK_ERROR_INCOMPATIBLE_SHADER_BINARY_EXT);
    default:
        return "VK_ERROR_UNKNOWN";
    }
}
} // namespace crisp::detail